"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ProtocolData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STORE_UPDATE_FIELD_NUMBER: builtins.int
    CONNECTION_INIT_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    CONNECTION_ACK_FIELD_NUMBER: builtins.int
    @property
    def store_update(self) -> global___StoreUpdate: ...
    @property
    def connection_init(self) -> global___ConnectionInit: ...
    @property
    def error(self) -> global___Error: ...
    @property
    def connection_ack(self) -> global___ConnectionAck: ...
    def __init__(
        self,
        *,
        store_update: global___StoreUpdate | None = ...,
        connection_init: global___ConnectionInit | None = ...,
        error: global___Error | None = ...,
        connection_ack: global___ConnectionAck | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "connection_ack",
            b"connection_ack",
            "connection_init",
            b"connection_init",
            "error",
            b"error",
            "message_type",
            b"message_type",
            "store_update",
            b"store_update",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "connection_ack",
            b"connection_ack",
            "connection_init",
            b"connection_init",
            "error",
            b"error",
            "message_type",
            b"message_type",
            "store_update",
            b"store_update",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["message_type", b"message_type"]
    ) -> (
        typing.Literal["store_update", "connection_init", "error", "connection_ack"]
        | None
    ): ...

global___ProtocolData = ProtocolData

@typing.final
class StoreUpdate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    NETWORK_ID_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    node_id: builtins.str
    network_id: builtins.str
    """Network/store identifier"""
    data: builtins.str
    """JSON serialized StoreData"""
    def __init__(
        self,
        *,
        node_id: builtins.str = ...,
        network_id: builtins.str = ...,
        data: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "data", b"data", "network_id", b"network_id", "node_id", b"node_id"
        ],
    ) -> None: ...

global___StoreUpdate = StoreUpdate

@typing.final
class ConnectionInit(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    NETWORK_ID_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    node_id: builtins.str
    network_id: builtins.str
    """Network this connection is for"""
    version: builtins.str
    def __init__(
        self,
        *,
        node_id: builtins.str = ...,
        network_id: builtins.str = ...,
        version: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "network_id", b"network_id", "node_id", b"node_id", "version", b"version"
        ],
    ) -> None: ...

global___ConnectionInit = ConnectionInit

@typing.final
class ConnectionAck(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    def __init__(
        self,
        *,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message"]) -> None: ...

global___ConnectionAck = ConnectionAck

@typing.final
class Error(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    code: builtins.str
    message: builtins.str
    details: builtins.str
    def __init__(
        self,
        *,
        code: builtins.str = ...,
        message: builtins.str = ...,
        details: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "code", b"code", "details", b"details", "message", b"message"
        ],
    ) -> None: ...

global___Error = Error
