# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meshmon.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "meshmon.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rmeshmon.proto\x12\x07meshmon"\x8a\x01\n\x0cProtocolData\x12*\n\x0bpacket_data\x18\x01 \x01(\x0b\x32\x13.meshmon.PacketDataH\x00\x12>\n\x15\x63onnection_validation\x18\x02 \x01(\x0b\x32\x1d.meshmon.ConnectionValidationH\x00\x42\x0e\n\x0cmessage_type"@\n\nPacketData\x12\x11\n\tpacket_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x11\n\tvalidator\x18\x03 \x01(\t")\n\x14\x43onnectionValidation\x12\x11\n\tvalidator\x18\x01 \x01(\t2S\n\x0eMeshMonService\x12\x41\n\rStreamUpdates\x12\x15.meshmon.ProtocolData\x1a\x15.meshmon.ProtocolData(\x01\x30\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "meshmon_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PROTOCOLDATA"]._serialized_start = 27
    _globals["_PROTOCOLDATA"]._serialized_end = 165
    _globals["_PACKETDATA"]._serialized_start = 167
    _globals["_PACKETDATA"]._serialized_end = 231
    _globals["_CONNECTIONVALIDATION"]._serialized_start = 233
    _globals["_CONNECTIONVALIDATION"]._serialized_end = 274
    _globals["_MESHMONSERVICE"]._serialized_start = 276
    _globals["_MESHMONSERVICE"]._serialized_end = 359
# @@protoc_insertion_point(module_scope)
