# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meshmon.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "meshmon.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rmeshmon.proto\x12\x07meshmon"\xa1\x01\n\x0cProtocolData\x12,\n\x0cstore_update\x18\x01 \x01(\x0b\x32\x14.meshmon.StoreUpdateH\x00\x12\x32\n\x0f\x63onnection_init\x18\x03 \x01(\x0b\x32\x17.meshmon.ConnectionInitH\x00\x12\x1f\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x0e.meshmon.ErrorH\x00\x42\x0e\n\x0cmessage_type"S\n\x0bStoreUpdate\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x12\n\nnetwork_id\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03"F\n\x0e\x43onnectionInit\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x12\n\nnetwork_id\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t"7\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x03 \x01(\t2S\n\x0eMeshMonService\x12\x41\n\rStreamUpdates\x12\x15.meshmon.ProtocolData\x1a\x15.meshmon.ProtocolData(\x01\x30\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "meshmon_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PROTOCOLDATA"]._serialized_start = 27
    _globals["_PROTOCOLDATA"]._serialized_end = 188
    _globals["_STOREUPDATE"]._serialized_start = 190
    _globals["_STOREUPDATE"]._serialized_end = 273
    _globals["_CONNECTIONINIT"]._serialized_start = 275
    _globals["_CONNECTIONINIT"]._serialized_end = 345
    _globals["_ERROR"]._serialized_start = 347
    _globals["_ERROR"]._serialized_end = 402
    _globals["_MESHMONSERVICE"]._serialized_start = 404
    _globals["_MESHMONSERVICE"]._serialized_end = 487
# @@protoc_insertion_point(module_scope)
