# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import meshmon_pb2 as meshmon__pb2

GRPC_GENERATED_VERSION = "1.75.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in meshmon_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MeshMonServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamUpdates = channel.stream_stream(
            "/meshmon.MeshMonService/StreamUpdates",
            request_serializer=meshmon__pb2.ProtocolData.SerializeToString,
            response_deserializer=meshmon__pb2.ProtocolData.FromString,
            _registered_method=True,
        )


class MeshMonServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamUpdates(self, request_iterator, context):
        """Bidirectional streaming for mesh updates"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MeshMonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "StreamUpdates": grpc.stream_stream_rpc_method_handler(
            servicer.StreamUpdates,
            request_deserializer=meshmon__pb2.ProtocolData.FromString,
            response_serializer=meshmon__pb2.ProtocolData.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "meshmon.MeshMonService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("meshmon.MeshMonService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class MeshMonService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamUpdates(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/meshmon.MeshMonService/StreamUpdates",
            meshmon__pb2.ProtocolData.SerializeToString,
            meshmon__pb2.ProtocolData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
