name: Build

on:
  push:
    tags: ['v*']
  pull_request:
  workflow_dispatch:
    inputs:
      push:
        description: 'Push'
        required: false
        type: boolean
        default: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: meshmon

jobs:
  quality-check:
    uses: ./.github/workflows/quality-check.yml
    secrets: inherit
  check-version:
    uses: ./.github/workflows/check-version.yml
  build:
    needs:
      - check-version
      - quality-check
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v5

    - uses: docker/setup-qemu-action@v3

    - uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        tags: |
          type=match,pattern=(v\d.\d.\d)
          type=match,pattern=(v\d.\d)
          type=match,pattern=(v\d)
          type=ref,event=pr

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        push: ${{ inputs.push != 'false' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=registry,ref=ghcr.io/ripplefcl/meshmon:buildcache
        cache-to: type=registry,ref=ghcr.io/ripplefcl/meshmon:buildcache,mode=max
        provenance: false

  release:
    if: github.event_name == 'push'
    needs: build
    permissions:
      contents: write
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      version: ${{ github.ref_name }}
