name: Build

on:
  push:
    tags: ['v*']
  pull_request:
  workflow_dispatch:
    inputs:
      push:
        description: 'Push'
        required: false
        type: boolean
        default: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: meshmon

jobs:
  quality-check:
    uses: ./.github/workflows/quality-check.yml
    secrets: inherit
  check-version:
    uses: ./.github/workflows/check-version.yml
  build:
    needs:
      - check-version
      - quality-check
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v5

    - uses: docker/setup-qemu-action@v3

    - uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        push: ${{ inputs.push != 'false' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=registry,ref=ghcr.io/ripplefcl/meshmon:buildcache
        cache-to: type=registry,ref=ghcr.io/ripplefcl/meshmon:buildcache,mode=max
        provenance: false

    - name: get version
      id: ev
      run: echo "::set-output name=version::$(python3 server/version.py)"

    - name: Create a Sentry.io release
      uses: getsentry/action-release@v3
      continue-on-error: true
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: beryjuio
        SENTRY_PROJECT: meshmon
        SENTRY_URL: https://sentry.beryju.io
      with:
        release: meshmon@${{ steps.ev.outputs.version }}

  release:
    if: github.event_name == 'push'
    needs: build
    permissions:
      contents: write
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      version: ${{ github.ref_name }}
